/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarRenderer: typeof import('./src/components/game/AvatarRenderer.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    ErrorModal: typeof import('./src/components/modals/ErrorModal.vue')['default']
    FullscreenModal: typeof import('./src/components/modals/FullscreenModal.vue')['default']
    GameAccountCard: typeof import('./src/components/game/GameAccountCard.vue')['default']
    GameInfoCard: typeof import('./src/components/game/GameInfoCard.vue')['default']
    GameLaunchBar: typeof import('./src/components/game/GameLaunchBar.vue')['default']
    GlassMessage: typeof import('./src/components/ui/GlassMessage.vue')['default']
    Icon: typeof import('./src/components/ui/Icon.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    LaunchProgressCard: typeof import('./src/components/game/LaunchProgressCard.vue')['default']
    Modal: typeof import('./src/components/modals/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    Slider: typeof import('./src/components/ui/Slider.vue')['default']
    TaskQueuePanel: typeof import('./src/components/panels/TaskQueuePanel.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
  }
}
