/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutEntryRow: typeof import('./src/components/settings/AboutEntryRow.vue')['default']
    Avatar: typeof import('./src/components/ui/Avatar.vue')['default']
    AvatarRenderer: typeof import('./src/components/game/AvatarRenderer.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    ConfirmDialog: typeof import('./src/components/modals/ConfirmDialog.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    ErrorModal: typeof import('./src/components/modals/ErrorModal.vue')['default']
    FullscreenModal: typeof import('./src/components/modals/FullscreenModal.vue')['default']
    GameAccountCard: typeof import('./src/components/game/GameAccountCard.vue')['default']
    GameInfoCard: typeof import('./src/components/game/GameInfoCard.vue')['default']
    GameLaunchBar: typeof import('./src/components/game/GameLaunchBar.vue')['default']
    Icon: typeof import('./src/components/ui/Icon.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    InstalledInstanceList: typeof import('./src/components/instances/InstalledInstanceList.vue')['default']
    InstanceCategoryManager: typeof import('./src/components/instances/InstanceCategoryManager.vue')['default']
    InstanceDetailModsTab: typeof import('./src/components/instances/InstanceDetailModsTab.vue')['default']
    InstanceDetailOverviewTab: typeof import('./src/components/instances/InstanceDetailOverviewTab.vue')['default']
    InstanceDetailProfileTab: typeof import('./src/components/instances/InstanceDetailProfileTab.vue')['default']
    InstanceDetailSettingsTab: typeof import('./src/components/instances/InstanceDetailSettingsTab.vue')['default']
    InstanceIcon: typeof import('./src/components/instances/InstanceIcon.vue')['default']
    InstanceInstallModal: typeof import('./src/components/instances/InstanceInstallModal.vue')['default']
    InstancePathSidebar: typeof import('./src/components/instances/InstancePathSidebar.vue')['default']
    InstanceResourcesTab: typeof import('./src/components/instances/InstanceResourcesTab.vue')['default']
    InstanceScreenshotsTab: typeof import('./src/components/instances/InstanceScreenshotsTab.vue')['default']
    InstanceServersTab: typeof import('./src/components/instances/InstanceServersTab.vue')['default']
    InstanceWorldsTab: typeof import('./src/components/instances/InstanceWorldsTab.vue')['default']
    LauncherPopupModal: typeof import('./src/components/modals/LauncherPopupModal.vue')['default']
    LaunchProgressCard: typeof import('./src/components/game/LaunchProgressCard.vue')['default']
    MarkdownContent: typeof import('./src/components/ui/MarkdownContent.vue')['default']
    Modal: typeof import('./src/components/modals/Modal.vue')['default']
    OnlineModSearch: typeof import('./src/components/mods/OnlineModSearch.vue')['default']
    PageHeader: typeof import('./src/components/layout/PageHeader.vue')['default']
    PlayerList: typeof import('./src/components/connect/PlayerList.vue')['default']
    Progress: typeof import('./src/components/ui/Progress.vue')['default']
    RequiredModDependencies: typeof import('./src/components/mods/RequiredModDependencies.vue')['default']
    ResourceInstanceSelect: typeof import('./src/components/resources/ResourceInstanceSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLayout: typeof import('./src/components/layout/SectionLayout.vue')['default']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    Slider: typeof import('./src/components/ui/Slider.vue')['default']
    Tag: typeof import('./src/components/ui/Tag.vue')['default']
    TaskQueuePanel: typeof import('./src/components/panels/TaskQueuePanel.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
    TitleBarTray: typeof import('./src/components/layout/TitleBarTray.vue')['default']
    WorldDownloadTab: typeof import('./src/components/resources/WorldDownloadTab.vue')['default']
  }
}
