name: Check quality

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup-node

      - name: Check quality
        run: pnpm check

      - name: Check i18n keys
        run: python scripts/check-i18n-keys.py
